"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.buildAsbaPdf = buildAsbaPdf;
const PDFDocument = require("pdfkit");
const rs = (n) => `Rs. ${n.toLocaleString('en-IN')}`;
/**
 * Prefilled ASBA Bid-cum-Application form (bank-submission route). The investor
 * prints, signs and hands it to their SCSB branch; the bank blocks the amount in
 * THEIR OWN account (self-PAN rule holds — no third-party funding).
 * Layout: single A4, uncompressed streams (verifiable/greppable output).
 */
function buildAsbaPdf(d) {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ size: 'A4', margin: 48, compress: false, info: { Title: `ASBA ${d.ipo.symbol} ${d.applicationId}` } });
        const chunks = [];
        doc.on('data', (c) => chunks.push(c));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);
        const W = doc.page.width - 96; // content width
        const label = (t) => doc.font('Helvetica').fontSize(8).fillColor('#666666').text(t.toUpperCase(), { characterSpacing: 0.5 });
        const value = (t) => doc.font('Helvetica-Bold').fontSize(11).fillColor('#111111').text(t);
        const rule = () => { doc.moveDown(0.6); doc.moveTo(48, doc.y).lineTo(48 + W, doc.y).lineWidth(0.5).strokeColor('#bbbbbb').stroke(); doc.moveDown(0.6); };
        // ---- header
        doc.font('Helvetica-Bold').fontSize(16).fillColor('#3c2e7e').text('INVESTOYARD');
        doc.font('Helvetica').fontSize(9).fillColor('#666666').text(`Channel: ${d.channelName}`);
        doc.moveUp(2);
        doc.font('Helvetica-Bold').fontSize(12).fillColor('#111111').text('ASBA BID-CUM-APPLICATION FORM', { align: 'right' });
        doc.font('Helvetica').fontSize(8).fillColor('#666666').text(`Ref: ${d.applicationId}`, { align: 'right' });
        rule();
        // ---- issue
        label('Issue');
        value(`${d.ipo.name} (${d.ipo.symbol})`);
        doc.font('Helvetica').fontSize(10).fillColor('#333333').text(`Price band: ${d.ipo.priceBandMin != null ? `${rs(Number(d.ipo.priceBandMin))} – ${rs(Number(d.ipo.priceBandMax ?? d.ipo.priceBandMin))}` : '—'}` +
            `   |   Lot size: ${d.ipo.lotSize ?? '—'}` +
            (d.ipo.closeDate ? `   |   Issue closes: ${d.ipo.closeDate}` : ''));
        rule();
        // ---- applicant (sole/first applicant — self-PAN)
        label('Sole / First Applicant');
        value(d.applicant.fullName);
        doc.font('Helvetica').fontSize(10).fillColor('#333333')
            .text(`PAN: ${d.applicant.pan}    Relationship: ${d.applicant.relationship}`)
            .text(`Depository: ${d.applicant.depository}    DP ID: ${d.applicant.dpId}    Client ID: ${d.applicant.clientId}`);
        rule();
        // ---- bid
        label('Bid Details');
        doc.font('Helvetica').fontSize(10).fillColor('#333333')
            .text(`Category: ${d.bid.category}    Applicant type: ${d.bid.applicantType}`)
            .text(`Lots: ${d.bid.lots}    Shares: ${d.bid.shares}    Price: ${d.bid.atCutoff ? 'CUT-OFF' : rs(Number(d.bid.bidPrice ?? 0))}`);
        doc.font('Helvetica-Bold').fontSize(12).fillColor('#111111').text(`Amount to block: ${rs(d.bid.amount)}`);
        rule();
        // ---- ASBA bank block
        label('ASBA Bank Account (SCSB)');
        doc.font('Helvetica').fontSize(10).fillColor('#333333')
            .text(`Account no.: ${d.bank.account ?? '________________________'}    IFSC: ${d.bank.ifsc ?? '____________'}`)
            .moveDown(0.4)
            .fontSize(9)
            .text('I/We authorise the SCSB to block the amount specified above in the bank account stated, ' +
            'as application money for the issue, and to unblock/transfer per allotment. The account belongs ' +
            'to the sole/first applicant named above (no third-party funding).', { width: W });
        doc.moveDown(1.6);
        const y = doc.y;
        doc.moveTo(48, y).lineTo(48 + 200, y).lineWidth(0.7).strokeColor('#333333').stroke();
        doc.moveTo(48 + W - 200, y).lineTo(48 + W, y).stroke();
        doc.fontSize(8).fillColor('#666666');
        doc.text('Signature of Sole/First Applicant', 48, y + 4, { width: 200 });
        doc.text('Bank use: seal, date & SCSB stamp', 48 + W - 200, y + 4, { width: 200, align: 'right' });
        // ---- footer
        doc.fontSize(7.5).fillColor('#999999').text(`Generated by Investoyard on ${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC. ` +
            'Each applicant applies with their own PAN, demat and bank account (SEBI ASBA norms). ' +
            'This form must be submitted to a Self-Certified Syndicate Bank branch before the issue closes.', 48, doc.page.height - 90, { width: W });
        doc.end();
    });
}
